### PR TITLE
Feature onKeyPress

### PR DESCRIPTION
**Pull request by devn0ll**
In the End just added the onKeyPressed Feature, and made a litte 100x100 window.

Other features ideas can be seen in the branch.

Didn’t need the Timer in the end, cause it will just make things complicated.

If we can make a consistent Tune without any annoying noises we should reopen the branch to make a onKeyPressed and onKeyReleased version of it.

### CODE REVIEW

**Comment by devn0ll** [comment]
@Sebov1c check out the code, i think that is the best idea for now.

If you merge it please don't close the branch we can use the branch later on if we can make a consistant tune.

**Comment by devn0ll** [comment]
guess i can delet line 11 and 29 in Main.java

**Comment by Sebov1c** [comment]
yes please.
some more minor things:
- fix scene.* import 
- comments would be nice at: KeyEvent-Handler, main and start

I will merge it this evening

**Comment by devn0ll** [comment]
will be done

**Pull request closed without merging**
